version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2022-01-04T07-41-07Z
    container_name: minio
    volumes:
      - ./data:/data
      - ./config:/root/.minio
      - /etc/localtime:/etc/localtime
    ports:
      - "9000:9000"
      - "9001:9001"
    privileged: true
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minioadmin123
    command: server /data --address ":9000" --console-address ":9001"