version: "3"
services:
  frps:
    image: snowdreamtech/frps:0.44.0
    container_name: frps
    volumes:
      - ../../volumes/frp/frps.ini:/etc/frp/frps.ini
    network_mode: host
    restart: always
