version: "3"
services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    volumes:
      - ../../volumes/frp/frps.ini:/etc/frp/frps.ini
    ports:
      - "9080:80"
      - "9443:443"
      - "7000:7000"
      - "7500:7500"
    restart: always
