version: "3"
services:
  nacos:
    image: nacos/nacos-server:1.1.4
    container_name: nacos
    volumes:
      - ../../volumes/nacos/logs:/home/nacos/logs
      - ../../volumes/nacos/data:/home/nacos/data
      - ../../volumes/nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
    restart: always
    environment:
      PREFER_HOST_MODE: hostname #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
      MODE: standalone
      MYSQL_SERVICE_HOST: 192.168.1.101
      MYSQL_SERVICE_DB_NAME: nacos_mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
