version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ../../volumes/mysql/conf:/etc/mysql/conf.d
      - ../../volumes/mysql/data:/var/lib/mysql
      - ../../volumes/mysql/logs/:/logs
    ports:
      - "3306:3306"
    restart: always
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=123456
