version: '3'

services:
  jenkins:
    image: jenkins/jenkins:2.440.1-jdk17
    container_name: jenkins
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "8050:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker
      - /etc/docker/daemon.json:/etc/docker/daemon.json
      - /docker/jenkins/jenkins_home:/var/jenkins_home
    privileged: true
    user: root
    restart: always
