version: "3"
services:
  redis:
    image: redis:5.0.3
    container_name: redis
    volumes:
      - ../../volumes/redis/redis.conf:/etc/redis/redis.conf
      - ../../volumes/redis/data:/data
    ports:
      - "6379:6379"
    restart: always
    privileged: true
    command:
      redis-server /etc/redis/redis.conf --appendonly yes --requirepass "123456"
